---
- name: Edge VPS (UFW + WireGuard + Docker + Traefik)
  hosts: vps
  become: true

  tasks:
    - name: Oppdater apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Installer basispakker
      apt:
        name:
          - ufw
          - curl
          - ca-certificates
          - gnupg
          - wireguard
          - iptables
        state: present

    # -------------------------
    # UFW (stramt og kjedelig)
    # -------------------------
    - name: Sett UFW default deny incoming
      ufw:
        direction: incoming
        policy: deny

    - name: Sett UFW default allow outgoing
      ufw:
        direction: outgoing
        policy: allow

    - name: Tillat WireGuard inn (UDP)
      ufw:
        rule: allow
        port: "{{ ufw_wireguard_port }}"
        proto: udp
        comment: "WireGuard VPN"

    - name: Tillat HTTP inn
      ufw:
        rule: allow
        port: "80"
        proto: tcp
        comment: "HTTP"

    - name: Tillat HTTPS inn
      ufw:
        rule: allow
        port: "443"
        proto: tcp
        comment: "HTTPS"

    - name: Slå på UFW logging (medium)
      ufw:
        logging: medium

    - name: Enable UFW
      ufw:
        state: enabled

    # -------------------------
    # WireGuard (VPS-side)
    # -------------------------
    - name: Slå på IPv4 forwarding (for framtidig routing om du trenger det)
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: true

    - name: Lag WireGuard config fra template
      template:
        src: templates/wg0.conf.j2
        dest: "/etc/wireguard/{{ wg_interface }}.conf"
        owner: root
        group: root
        mode: "0600"

    - name: Enable & start WireGuard
      systemd:
        name: "wg-quick@{{ wg_interface }}"
        enabled: true
        state: started

    # -------------------------
    # Docker (offisiell repo)
    # -------------------------
    - name: Legg til Docker GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Legg til Docker repo
      shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Oppdater apt cache etter Docker repo
      apt:
        update_cache: true

    - name: Installer Docker + compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Sørg for at Docker kjører
      systemd:
        name: docker
        enabled: true
        state: started

    # -------------------------
    # Traefik (docker compose)
    # -------------------------
    - name: Lag Traefik-mappe
      file:
        path: "{{ traefik_dir }}"
        state: directory
        mode: "0755"

    - name: Lag acme-mappe
      file:
        path: "{{ traefik_dir }}/acme"
        state: directory
        mode: "0700"

    - name: Lag tom acme.json hvis mangler (LE trenger write)
      file:
        path: "{{ traefik_dir }}/acme/acme.json"
        state: touch
        mode: "0600"

    - name: Kopier Traefik statisk config
      template:
        src: templates/traefik.yml
        dest: "{{ traefik_dir }}/traefik.yml"
        mode: "0644"

    - name: Kopier Traefik dynamic config
      template:
        src: templates/dynamic.yml
        dest: "{{ traefik_dir }}/dynamic.yml"
        mode: "0644"

    - name: Kopier docker compose for Traefik
      template:
        src: templates/docker-compose.traefik.yml
        dest: "{{ traefik_dir }}/docker-compose.yml"
        mode: "0644"

    - name: Start Traefik via docker compose
      shell: |
        cd "{{ traefik_dir }}"
        docker compose up -d
